version: 1.0.{build}
skip_commits:
  message: /.*dumps.*/

image:
  - Visual Studio 2015
  - Visual Studio 2017

build_script:
  - cd Source\ExceptionDumper32
  - dotnet restore
  - dotnet msbuild
  - cd ..\..\
  - msbuild Source\NativeDumpTest\NativeDumpTest.x64.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x64.Release.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x86.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x86.Release.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo
  - SET gccpath=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
  - SET project_root=C:\projects\windbgcs-dumps
  - SET ORIGINAL_PATH=%PATH%
  - SET PATH=%gccpath%;%ORIGINAL_PATH%
  - IF EXIST %gccpath% ( %gccpath%\g++ %project_root%\Source\NativeDumpTest\NativeDumpTest.cpp -o %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -std=c++11 -g )
  - IF EXIST %gccpath% ( %project_root%\Source\ExceptionDumper\bin\Debug\net461\ExceptionDumper.exe -a %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -d %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.mdmp )
  - SET gccpath=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
  - SET PATH=%gccpath%;%ORIGINAL_PATH%
  - IF EXIST %gccpath% ( %gccpath%\g++ %project_root%\Source\NativeDumpTest\NativeDumpTest.cpp -o %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -std=c++11 -g )
  - IF EXIST %gccpath% ( %project_root%\Source\ExceptionDumper32\bin\Debug\net461\ExceptionDumper32.exe -a %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -d %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.mdmp )

artifacts:
  - path: '**\*.*exe'
  - path: '**\*.*pdb'
  - path: '**\*.*dmp'
