version: 1.0.{build}
skip_commits:
  message: /.*dumps.*/

image:
  - Visual Studio 2015
  - Visual Studio 2017

build_script:
  - cd Source\ExceptionDumper32
  - dotnet restore
  - dotnet msbuild
  - cd ..\..\
  - msbuild Source\NativeDumpTest\NativeDumpTest.x64.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x64.Release.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x86.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x86.Release.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo

artifacts:
  - path: '**\*.*dmp'
